### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Jobling** [Jobling/PSIS#1]
- [ ] Create auxiliary function to close file descriptors on _database.c_;

- [ ] Figure how to use the number of written bytes _n_ on `n = write(file, buffer, buffer_size);` present in: _write_log_, _write_backup_ and _restore_database_;

- [ ] Create _psiskv_front_server.c_

- [ ] Complete server with _front server_ and _data server_.

- [ ] Implement heartbeat;

- [ ] Review mutex synchronization on _database.c_;

- [ ] Develop test cases: _client_write_after_write_ and etc.
